In [1]:
import numpy as np

Problem 4 on midterm
Consider a finite horizon LQR problem over a horizon of H = 20 with dynamics:
x1(t+1) = x1(t) - 0.25x2(t) + 0.4u1(t) 
x2(t+1) = x2(t) + 0.1u1(t) + 0.1u2(t)

and cost:

c(x(t), u(t)) = 2x1^2(t) + 5x2^2(t) + 10u1^2(t) + 8u2^2(t)

x(t), u(t) are in R2 (2 dimensions)

Part 1 asked us to find the transition matrices A, B and cost matrices Q, and R. Note, there is no noise in these dynamics.

Those matrices can be found by simply looking at A, B, Q, R as identity matrices, then adjusting those identity matrices to match the dynamics and cost equations. 

They are listed below:

In [10]:
A = np.array([[1, -0.25], [0, 1]])
B = np.array([[0.4, 0], [0.1, 0.1]])

Q = np.array([[2, 0], [0, 5]])
R = np.array([[10, 0], [0, 8]])
print("Transition matrix A\n", A, "\n")
print("Transition matrix B\n", B, "\n")
print("Cost matrix Q\n", Q, "\n")
print("Cost matrix R\n", R, "\n")

Transition matrix A
 [[ 1.   -0.25]
 [ 0.    1.  ]] 

Transition matrix B
 [[0.4 0. ]
 [0.1 0.1]] 

Cost matrix Q
 [[2 0]
 [0 5]] 

Cost matrix R
 [[10  0]
 [ 0  8]] 



Part 2 asks to compute the matrix P(t) based on the Riccati equation for t = 20, 19, and 18
Note that the Ph = Q. We have computed Q above.

Furthermore, Pt = A.T @ Pt+1 @ A + Q - A.T @ Pt + 1 @ B @ np.linalg.inv(B.T @ Pt+1 @ B + R) @ B.T @ Pt+1 @ A 
With this equation, we can compute Pt for t = 20, 19, and 18

In [7]:
P20 = Q
Pt_plus_1 = Q
print("P20 is\n", Q, "\n")

P19 = A.T @ Pt_plus_1 @ A + Q - A.T @ Pt_plus_1 @ B @ np.linalg.inv(B.T @ Pt_plus_1 @ B + R) @ B.T @ Pt_plus_1 \
@ A

print("P19 is \n", P19, "\n")
Pt_plus_1 = P19

P18 = A.T @ Pt_plus_1 @ A + Q - A.T @ Pt_plus_1 @ B @ np.linalg.inv(B.T @ Pt_plus_1 @ B + R) @ B.T @ Pt_plus_1 \
@ A

print("P18 is \n", P18)

P20 is
 [[2 0]
 [0 5]] 

P19 is 
 [[ 3.93828166 -0.52290479]
 [-0.52290479 10.08544372]] 

P18 is 
 [[ 5.72077621 -1.55911559]
 [-1.55911559 15.44858428]]


Part 3 asks us to compute the optial control gain K*(t) (note * is for optimal, not multiply) for t = 19, 18

We can compute K*(t), the optimal control gain, by:
K_opt_t = np.linalg.inv(B.T @ Pt_plus_1 @ B + R) @ B.T @ Pt_plus_1 @ A

The computations for optimal control gain at t = 19, 18 are done below:

In [9]:
# K_opt_19:
Pt_plus_1 = P20
K_opt_19 = np.linalg.inv(B.T @ Pt_plus_1 @ B + R) @ B.T @ Pt_plus_1 @ A
print("controller gain at t = 19\n", K_opt_19, "\n")

# K_opt_18:
Pt_plus_1 = P19
K_opt_18 = np.linalg.inv(B.T @ Pt_plus_1 @ B + R) @ B.T @ Pt_plus_1 @ A
print("controller gain at t = 18\n", K_opt_18, "\n")


controller gain at t = 19
 [[ 0.07714792  0.02863098]
 [-0.00047918  0.06193397]] 

controller gain at t = 18
 [[ 0.14254183  0.03822343]
 [-0.00786152  0.12573507]] 



Part 4:
Write the optimal policy as a function of state for t = 19, t = 18

The optimal polcy is a linear controller defined by:
pi_opt = -K_opt_t @ xt, where xt is a state vector, K_opt_t is the controller gain for a particular time step (was computed above). The output pi_opt will be a vector for the optimal action.

Code to compute this is below

In [ ]:
pi_opt_19 = -K_opt_19 @ xt_19 # note, we would actually need state values to compute this
pi_opt_18 = -K_opt_18 @ xt_18 # note, we would actually need state values to compute this

Part 5: Write the optimal value function as a function of state for t = 20, 19, and 18.

Optimal value function is defined as:
v_opt_t = x.T @ Pt @ x + noise_var * (sum of traces of P from t' = t + 1 to H).
However, we do not have noise in this problem, therefore, v_opt_t = x.T @ Pt @ x
The code for this is written below:

In [ ]:
# note, we would not be able to compute these until we have an input state x
v_opt_20 = x.T @ P20 @ x
v_opt_19 = x.T @ P19 @ x
v_opt_18 = x.T @ P18 @ x

Question 1-2: We have a Markov Decision process with states = {action, horror, comedy} and actions = {movieA, movieB, movieC, movieD}. The initial state distribution mu_0 is uniform across states. The transition function p(s' | s, a) has been computed. 

We are given a policy pi(a | s). 

Specifically:
If the user asks for action, the action is movieA = 0.45, movieB = 0.45, movieD = 0.1
If the user asks for horror, the action is movieA = movieB = movieC = movieD = 0.25
If the user asks for comedy, the action is movie B = 0.3, movieC = 0.7

We can compute R_pi(s) as a 3 dimension vector. Each component is computed by summing over actions
We can compute P_pi(s,s') as a 3 by 3 matrix. Each component represents the probability of transitioning from 
state s to state s' given the transition function and policy. The components of R_pi and P_pi are hand computed. The code below is inserting the hand computed values in.

In [20]:
R_pi = np.zeros((3,1))
R_pi[0] = 1
R_pi[1] = 0.8
R_pi[2] = 0.5

P_pi = np.array([[0, 0.5, 0.5],
                [.45, .1, .45],
                [.375, .375, .25]])

print("R_pi vector:\n", R_pi, "\n")
print("P_pi\n", P_pi, "\n")
I = np.eye(P_pi.shape[0])
gamma = 0.98
V_pi = np.linalg.inv(I - gamma * P_pi) @ R_pi
states = {0: 'comedy', 1: 'action', 2: 'horror'}
for i in range(V_pi.shape[0]):
    print("Value for state", states[i], ":", V_pi[i])

R_pi vector:
 [[1. ]
 [0.8]
 [0.5]] 

P_pi
 [[0.    0.5   0.5  ]
 [0.45  0.1   0.45 ]
 [0.375 0.375 0.25 ]] 

Value for state comedy : [37.28921636]
Value for state action : [37.15922497]
Value for state horror : [36.90040025]
